[package]
name = "untitled1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.31.0"
image = "0.24.0"
nalgebra = "0.30.1"
rand = "0.8.4"
arrayvec = "0.7.2"
